<div style="width:450px;margin:auto" class="page-header">
   <h1>Welcome to Roulette!</h1>
</div>

<div style="width:450px;margin:auto">
<img width="350" src="https://bfgblog-a.akamaihd.net/uploads/2013/11/6-4-European-Roulette.png">

<form action="index/checkuser">
<input type="text" placeholder="login" name="login">
<input type="password" placeholder="****" name="password">
<br/>
<button type="submit">Login</button>&nbsp;
<button type="button">Register</button>
</form>
</div>
<?php= $result ?>
